<div class="navigation-bar dark">
    <div class="navigation-bar-content container">
        <?php Print Html::link("", "<span class='icon-grid-view'></span> Sistemas Metro de Facturación <sup>2.0</sup>", "class='element'") ?>
        <span class="element-divider"></span>

        <a class="element1 pull-menu" href="#"></a>
        <ul class="element-menu">
            <li><?php print Html::link("", "Inicio") ?><!--<a class="dropdown-toggle" href="#">Base CSS</a>
            <ul class="dropdown-menu dark" data-role="dropdown">
                    <li><a href="requirements.html">Requirements</a></li>
                    <li class="divider"></li>
                    <li><a href="responsive.html">Responsive</a></li>
                    <li class="disabled"><a href="layouts.html">Layouts and templates</a></li>
                    <li class="divider"></li>
                    <li><a href="icons.html">Icons</a></li>
                </ul>-->
            </li>
            <li><a href="#">Templates</a></li>
        </ul>
        <!-- Con registro de session -->
        <span class="element-divider place-right"></span>
        <div class="element place-right">
            <a class="dropdown-toggle" href="#"><span class="icon-cog"></span></a>
            <ul class="dropdown-menu place-right" data-role="dropdown" style="display: none;">
                <li><a href="#">Products</a></li>
                <li><a href="#">Download</a></li>
                <li><a href="#">Support</a></li>
                <li><a href="#">Buy Now</a></li>
            </ul>
        </div>
        <button class="element image-button image-left place-right">Sergey Pimenov <img src="images/me.jpg"></button>
        <!-- Con registro de session -- -->
        <!--
          <div class="no-tablet-portrait no-phone">
            <a title="Nuget.org" href="https://www.nuget.org/packages/Metro.UI.CSS/" class="element place-right"><span class="icon-box-add"></span></a>
            <span class="element-divider place-right"></span>
            <a title="GitHub" href="https://github.com/olton/Metro-UI-CSS" class="element place-right"><span class="icon-github"></span></a>
            <span class="element-divider place-right"></span>
            <a title="CSS3 validator" href="http://jigsaw.w3.org/css-validator/validator?uri=metroui.org.ua&profile=css3&usermedium=all&warning=no&vextwarning=" class="element place-right"><span class="icon-css3"></span></a>
            <span class="element-divider place-right"></span>
            <div class="element place-right" title="GitHub Stars"><span class="icon-star"></span> <span class="github-watchers">0</span></div>
            <!--<span class="element-divider place-right"></span>-->
            <!--<div class="element place-right" title="GitHub Forks"><span class="icon-share-2"></span> <span class="github-forks">0</span></div>-->
        </div>
    </div>
</div>
