<div class="navigation-bar dark">
    <div class="navigation-bar-content container">
        <?php Print Html::link("", "<i class='icon-rocket'></i> Servicios Especializados<sup><br />Webmaster</sup>", "class='element'") ?>
        <span class="element-divider"></span>

        <a class="element1 pull-menu" href="#"></a>
        <ul class="element-menu">
            <li><?php print Html::link("", "Inicio") ?></li>
            <li><a href="#">Templates</a></li>
        </ul>
        <!-- Con registro de session -->
        <?php if(!Auth::is_valid()): ?>

        <span class="element-divider place-right"></span>
        <div class="element place-right">
            <?php print Html::link("login", "Login  <span class='icon-locked-2'></span>") ?>
        </div>
        <?php else: ?>
        <?php $user = Auth::get('user'); ?>
        <span class="element-divider place-right"></span>
        <div class="element place-right">
            <a class="dropdown-toggle" href="#"><span class="icon-cog"></span></a>
            <ul class="dropdown-menu place-right" data-role="dropdown" style="display: none;">
                <li><?php print Html::link("users", "Usuarios") ?></li>
                <li><?php print Html::link("logs", "Logs de Sistema") ?></li>
                <li><?php print Html::link("logout", "Logout") ?></li>
            </ul>
        </div>
        <button class="element image-button image-left place-right"><a href=""><?php print $user ?><img src="images/me.jpg"></a></button>
        <?php endif?>

        </div>
    </div>
</div>
