<div class="navigation-bar dark">
    <div class="navigation-bar-content container">
        <?php Print Html::link("", "<span class='icon-grid-view'></span> Sistemas Metro de Facturación <sup>2.0</sup>", "class='element'") ?>
        <span class="element-divider"></span>

        <a class="element1 pull-menu" href="#"></a>
        <ul class="element-menu">
            <li><?php print Html::link("", "Inicio") ?></li>
            <li><a href="#">Templates</a></li>
        </ul>
        <!-- Con registro de session -->
        <?php if(!Auth::is_valid()): ?>

        <span class="element-divider place-right"></span>
        <div class="element place-right">
            <?php print Html::link("login", "Login  <span class='icon-locked-2'></span>") ?>
        </div>
        <?php else: ?>
        <span class="element-divider place-right"></span>
        <div class="element place-right">
            <a class="dropdown-toggle" href="#"><span class="icon-cog"></span></a>
            <ul class="dropdown-menu place-right" data-role="dropdown" style="display: none;">
                <li><a href="#">Products</a></li>
                <li><a href="#">Download</a></li>
                <li><a href="#">Support</a></li>
                <li><a href="#">Buy Now</a></li>
            </ul>
        </div>
        <button class="element image-button image-left place-right">Sergey Pimenov <img src="images/me.jpg"></button>
        <?php endif?>

        </div>
    </div>
</div>
