
<?php if(!Auth::is_valid()): ?>
	<div class="span8 offset4">
		<div><?php View::content() ?></div>
		<?php Print Form::open("login") ?>
		<frameset class="bg-darkPink">
			<legend>Login de Sistema</legend>
			<label>Usuario</label>
				<div class="input-control text" data-role="input-control">
                    <?php Print Form::text("user") ?>
                    <button class="btn-clear" tabindex="-1" type="button"></button>
                 </div>
			<label>Pasword</label>
			<div class="input-control password" data-role="input-control">
               	<?php Print Form::pass("password") ?>
                <button class="btn-reveal" tabindex="-1" type="button"></button>
            </div>
            <?php Print Form::submit("Enviar") ?>
		</frameset>
		<?php Print Form::close() ?>
	</div>
<?php else: ?>
	<h3>Estas logueado</h3>
<?php endif ?>
